### PR TITLE
Cleanup unnecessary code and prepare for iOS10

### PR DESCRIPTION
**Pull request by williamrijksen**
### Context

The code was old and the delegate-proxy is not necessary anymore. Cleaned up some user-specific  code as well and prepared for iOS 10.

### CODE REVIEW

**Comment by PietroGranati** [comment]
Quote this

**Comment by jvandijk** [comment]
@PietroGranati what do you mean by quote this?

**Comment by chmiiller** [comment]
please merge it =)

**Comment by jvandijk** [comment]
Verified!

**Pull request merged**
